### ISSUE TITLE
More Badges at Once Player

### ISSUE THREAD

**Issue by MarcPlaying** [osuripple/hanayo#4]
Only one Badge at once work at a Player!

![grafik](https://user-images.githubusercontent.com/35847627/42417976-7c5c8e68-8296-11e8-96d1-49cb2b1b7f82.png)
Only one Badge is possible to save in the Database but the Admin Panel Shows more
![grafik](https://user-images.githubusercontent.com/35847627/42417981-9fbbedfe-8296-11e8-8484-fa637b9db149.png)

**Comment by thehowl** [comment]
However...

![image](https://user-images.githubusercontent.com/4681308/42418253-8bd898ae-829c-11e8-8261-d8c47bb9ebe7.png)

[How is this magic possible, I wonder?](https://en.wikipedia.org/wiki/Many-to-many_%28data_model%29)

If it doesn't work for you, it probably means you have set a primary key on user, when it needs to be `PRIMARY KEY(user, badge)`.

Please don't create issues if it's something that's not even replicable on Ripple itself.
