### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by yaj0928** [osuripple/hanayo#5]
`Whoops, an error slipped in. You might have been registered, though. I don't know.
`
`hanayo v1.8.6
Development environment detected. Starting fsnotify on template folder...
Importing templates...
Setting up rate limiter...
Exporting configuration...
Intialisation: 185.0289ms
Starting session system...
Listening on 0.0.0.0:8085
[GIN] 2019/01/07 - 19:27:54 |[97;42m 200 [0m|    262.6237ms |    172.30.1.254 |[97;46m POST    [0m /register
[GIN] 2019/01/07 - 19:27:54 |[97;42m 200 [0m|     255.836ms |    172.30.1.254 |[97;44m GET     [0m /static/ripple.css?1546856703460873100
[GIN] 2019/01/07 - 19:27:54 |[97;42m 200 [0m|    244.1215ms |    172.30.1.254 |[97;44m GET     [0m /static/semantic.min.css?1546856703460873100
[GIN] 2019/01/07 - 19:27:54 |[97;42m 200 [0m|     334.916ms |    172.30.1.254 |[97;44m GET     [0m /static/dist.min.js?1546856703460873100`

i cant register
![image](https://user-images.githubusercontent.com/33867923/50763202-7d77e980-12b2-11e9-8c3c-c8b9bd06050c.png)

**Comment by Nightsh0t** [comment]
Just as an FYI, the Ripple Team will **never** supply and support for their software.

Look into it. Turn on debug mode in hanayo it will help tons. That's all I will say.

Have a wonderful adventure with their code! It was one hell of a ride for me when I started.
-Night

**Comment by yaj0928** [comment]
thx
